### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by xleonx0x**
added navbar component with dynamic profile icons 🔥

### CODE REVIEW

**Comment by xleonx0x** [comment]
i did an oopsie and committed both summary and navbar to this, how do i undo this 😔

**Comment by lachlanshoesmith** [comment]
> i did an oopsie and committed both summary and navbar to this, how do i undo this 😔

you can use `git reset --hard <insert commit hash of where you want to go back to>` and then `git push` when you're done. note that the first command will undo all your work locally that youve done so make sure youre happy before you push! i also recommend making a local copy of your changes (ie copying the repo directory) so you can copy paste the changes you do wanna add to your commits more carefully without potentially losing them

let me know when you've figured it out and ill review 😁

**Comment by xleonx0x** [comment]
> > i did an oopsie and committed both summary and navbar to this, how do i undo this 😔
> 
> you can use `git reset --hard <insert commit hash of where you want to go back to>` and then `git push` when you're done. note that the first command will undo all your work locally that youve done so make sure youre happy before you push! i also recommend making a local copy of your changes (ie copying the repo directory) so you can copy paste the changes you do wanna add to your commits more carefully without potentially losing them
> 
> let me know when you've figured it out and ill review 😁

**Comment by xleonx0x** [comment]
oops

**Comment by xleonx0x** [comment]
> > i did an oopsie and committed both summary and navbar to this, how do i undo this 😔
> 
> you can use `git reset --hard <insert commit hash of where you want to go back to>` and then `git push` when you're done. note that the first command will undo all your work locally that youve done so make sure youre happy before you push! i also recommend making a local copy of your changes (ie copying the repo directory) so you can copy paste the changes you do wanna add to your commits more carefully without potentially losing them
> 
> let me know when you've figured it out and ill review 😁

ok done, you can review now :D

**Comment by lachlanshoesmith** [comment]
good to go now, ill merge in - i recommend having a look through some of my commits to see what i changed. the main thing i did was remove redundant classes for individual elements that could have been specified by just using different [combinators](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators). i also got rid of some styles that weren't really doing anything/rewrote some css to avoid unnecessary repetition

i also changed the logic with which you picked a level for the title (which i renamed level->size and title->logo, which make a bit more sense to me - i hope this is okay) to instead just involve just getting a corresponding size from a hash table. this is safe thanks to typescript ensuring we never get a size we wont expect 😁😁😁

i think thats abt it - amazing work all in all chris !! 👏👏

**Pull request merged**
